# Message to hiring manager:
# This is a demo pipeline and illustrated to show what a workflow could look like on tag/release

# This has not been tested so I can not garantee this work. Especially after my new understanding of how 'workflow_run' works
name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and Push Image"]
    types:
      - completed

defaults:
  run:
    shell: bash -ileo pipefail "{0}"

jobs:
  deploy_to_production:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: run k8s
        run: |
          envsubst < k8s/deployment.yaml | kubectl apply -f -
          envsubst < k8s/services.yaml | kubectl apply -f -
          envsubst < k8s/ingressroute.yaml | kubectl apply -f -