name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and Push Image"]
    types:
      - completed

defaults:
  run:
    shell: bash -ileo pipefail "{0}"

jobs:
  deploy_to_production:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: |
          echo "check it got here"