name: Lint and SAST

on: [push, pull_request]

jobs:
    sast-and-lint-checks:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3

            - name: Python Setup
              uses: actions/setup-python@v2
              with:
                python-version: '3.10.12'

            - name: Upgrade pip
              run: python -m pip install --upgrade pip
            
            - name: Install flake8 for linter and bandit for SAST
              run: pip install flake8 bandit

            - name: Apply Lint on code
              run: flake8 .

            - name: Run SAST with Bandit
              run: bandit -r .

            - name: Build
              run: echo "Flask web app doesn't need to be built but will build a docker container image in next file"
