name: Lint and SAST

on: [push, pull_request]

jobs:
    sast-and-lint-checks:
        runs-on: ubuntu-22.04
            - name: Checkout code
            - uses: actions/checkout@v3

            - name: Python Setup
              uses: actions/setup-python@v2
              with:
                python-version: '3.10.12'

            - name: Upgrade pip
              run: python -m pip install --upgrade pip
            
            - name: Install flake8 for linter
              run: pip install flask8

            - name: Apply Lint on code
              run: flake8 .
